# SPDX-License-Identifier: MIT
name: Release

on:
  push:
    tags:
    - '*.*.*'
    paths-ignore:
    - '**.md'
    - '.gitignore'

env:
  REGISTRY: ghcr.io

jobs:
  release:
    name: Create release
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        set -euo pipefail
        IMAGE_BASE_NAME="$(sed -n "s/^FROM \(.*\)/\1/p" Dockerfile | tail -n 1)"
        echo "IMAGE_BASE_NAME=${IMAGE_BASE_NAME}" >>"${GITHUB_ENV}"
        echo "IMAGE_BASE_DIGEST=$(docker pull ${IMAGE_BASE_NAME} | sed -n "s/^Digest: \(.*\)$/\1/p")" >>"${GITHUB_ENV}"
        cat "${GITHUB_ENV}"

    - name: Setup cosign
      uses: sigstore/cosign-installer@v2
      with:
        cosign-release: 'v1.11.0'
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/yamllint-test
        labels: |
          org.opencontainers.image.authors=Felix Furrer
          org.opencontainers.image.created=1970-01-01T00:00:00Z
          org.opencontainers.image.description=A linter for YAML files.
          org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/main/README.md
          org.opencontainers.image.licenses=GPL-3.0-or-later
          org.opencontainers.image.title=yamllint
          org.opencontainers.image.vendor=Felix Furrer
          org.opencontainers.image.base.name=${{ env.IMAGE_BASE_NAME }}
          org.opencontainers.image.base.digest=${{ env.IMAGE_BASE_DIGEST }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Build Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

    - name: Sign the published Docker image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        echo "${{ steps.metadata.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
